# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/foolin/gin-template"

[[constraint]]
  branch = "master"
  name = "github.com/mgouline/slack"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/heroku/x"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/traversals/blaster"
  go-version = "1.10"
  install = [ "./..." ]
