name: pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use .env.example
        run: cp .env.example .env
      
      - name: Test
        run: make test
